apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/manifests/stacks/kubernetes/application/oidc-authservice?ref=v1.2-branch

configMapGenerator:
  - name: oidc-authservice-parameters
    envs:
      - params.env

generatorOptions:
  disableNameSuffixHash: true
