apiVersion: kubermatic.k8s.io/v1
kind: AddonConfig
metadata:
  name: kubeflow-operator
spec:
  description: "KubeFlow Operator"
  formSpec:
    - displayName: "Enable TLS"
      internalName: "EnableTLS"
      helpText: "Certificate will be issued for the Dashboard URI domain. Make sure to set up you DNS accordingly."
      required: false
      type: bool
    - displayName: "Dashboard URI"
      internalName: "DashboardURI"
      helpText: "URI (domain name) that will be used to access the KubeFlow dashboard. Make sure to set up you DNS accordingly."
      required: false
      type: string
    - displayName: "Istio Ingress Gateway Service Type"
      internalName: "IstioIngressGatewayServiceType"
      helpText: "Type of the istioingressgateway service, used to access KubeFlow dashboard. It can be set to ClusterIP, NodePort or LoadBalancer."
      required: false
      type: string
    - displayName: "OIDC Provider URL"
      internalName: "OIDCProviderURL"
      helpText: "URL of external OIDC provider, e.g. Kubermatic Dex instance. Make sure that DashboardURI is specified if you are using this. If not specified, no authentication is used (very insecure!)."
      required: false
      type: string
    - displayName: "OIDC Secret"
      internalName: "OIDCSecret"
      helpText: "Secret string shared between the OIDC provider and KubeFlow. If not provided, the default from KubeFlow manifests is used (insecure!).."
      required: false
      type: string
